name: publish to pypi

on:
  push:
    branches:
      - '*'
  workflow_dispatch:


jobs:
  build:
    strategy:
      matrix:
        pyver: ['3.8', '3.9', '3.10', '3.11']
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: Jimver/cuda-toolkit@v0.2.11
        id: cuda-toolkit
        with:
          cuda: '11.8.0'
      - name: Build
        run: |
          echo $env:CUDA_PATH
          # mkdir build
          # cd build
          # ..\builder\windows\generate.ps1
          # cmake --build . --config Release -- /m
          # cd ..
          # rm build -Force -Recurse
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.pyver }}
      - name: Pack wheel
        run: |
          mkdir build/wheel
          python --version > build/wheel/${{ matrix.pyver }}.txt
          # python setup.py bdist_wheel -d build/wheel
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          path: build/wheel/*
          retention-days: 1

  publish:
    runs-on: ubuntu-latest
    environment: 'prod'
    needs:
      - build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Display artifacts
        run: ls artifact/ -lh
      # - name: Set up python3.8
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.8'
      # - name: Upload to pypi
      #   run: |
      #     pip install twine
      #     twine upload artifact/* -u __token__ -p ${{ secrets.pypi_password }}
